package puzzle.math;
import puzzle.Puzzle;

/**
 * Estimate Pi via Monte-Carlo sampling of random points in a unit quarter-circle (threaded variant included).
 * estimatePi: single-threaded (NUM*10 samples). estimatePi_B: 10 worker threads, then aggregate.
 */
public class EstimatePiPuzzle extends Thread implements Puzzle {


    int NUM = 1000000;
    int total;

    /**
     * Return how many random samples generated by this worker fell inside the unit quarter-circle.
     */
    public int getTotal() {
        return total;
    }

    @Override
    /**
     * Print both the single-thread and multi-thread Monte-Carlo estimates.
     */
    public void resolve() {
        try {
            System.out.println(String.format("PI (single-thread) is roughly %.4f", estimatePi()));
            System.out.println(String.format("PI (parallel)      is roughly %.4f", estimatePi_B()));
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
            throw new IllegalStateException("Pi estimation was interrupted.", e);
        }
    }

    /**
     * Worker-thread entry point: generate {@code NUM} random points in the unit square and count how
     * many land inside the unit quarter-circle.
     */
    @Override
    public void run() {
        for (int i = 0; i < NUM; i++) {
            double x = Math.random();
            double y = Math.random();
            if (x * x + y * y < 1) {
                total++;
            }
        }
    }

    /**
     * Single-thread Monte-Carlo estimate of pi.
     */
    private double estimatePi() throws InterruptedException {
        int samples = NUM * 10;
        int inside = 0;
        for (int i = 0; i < samples; i++) {
            double x = Math.random();
            double y = Math.random();
            if (x * x + y * y < 1) {
                inside++;
            }
        }
        return 4.0 * inside / samples;      // fraction of unit-square points inside the quarter circle is pi/4
    }

    /**
     * Multi-thread Monte-Carlo estimate of pi using 10 workers. All workers are started first, then
     * joined, so the sampling actually runs in parallel rather than serially.
     */
    private double estimatePi_B() throws InterruptedException {

        EstimatePiPuzzle[] threads = new EstimatePiPuzzle[10];
        for (int i = 0; i < 10; i++) {
            threads[i] = new EstimatePiPuzzle();
        }
        for (Thread t : threads) {
            t.start();                      // start all workers first ...
        }
        for (Thread t : threads) {
            t.join();                       // ... then wait for them -> they run in parallel
        }

        int sum = 0;
        for (EstimatePiPuzzle t : threads) {
            sum += t.getTotal();
        }

        return 4.0 * sum / (NUM * 10);
    }
}
